remote_theme: aljazceru/hacker-gh-pages-theme
plugins:
- jekyll-remote-theme

show_downloads: false
google_analytics: G-CLB7CSRLS5
plausible_script_url: https://analytics.cypherpunk.cloud/js/script.js
plausible: cryptoanarchy.info
